
QUEEN_MOVES = [
                [
                    (row + 1, col + 1),
                    (row + 2, col + 2),
                    (row + 3, col + 3),
                    (row + 4, col + 4),
                    (row + 5, col + 5),
                    (row + 6, col + 6),
                    (row + 7, col + 7),
                ],
                [
                    (row - 1, col - 1),
                    (row - 2, col - 2),
                    (row - 3, col - 3),
                    (row - 4, col - 4),
                    (row - 5, col - 5),
                    (row - 6, col - 6),
                    (row - 7, col - 7),
                ],
                [
                    (row + 1, col - 1),
                    (row + 2, col - 2),
                    (row + 3, col - 3),
                    (row + 4, col - 4),
                    (row + 5, col - 5),
                    (row + 6, col - 6),
                    (row + 7, col - 7),
                ],
                [
                    (row - 1, col + 1),
                    (row - 2, col + 2),
                    (row - 3, col + 3),
                    (row - 4, col + 4),
                    (row - 5, col + 5),
                    (row - 6, col + 6),
                    (row - 7, col + 7),
                ],
                [
                    (row + 1, col),
                    (row + 2, col),
                    (row + 3, col),
                    (row + 4, col),
                    (row + 5, col),
                    (row + 6, col),
                    (row + 7, col)
                ],
                [
                    (row - 1, col),
                    (row - 2, col),
                    (row - 3, col),
                    (row - 4, col),
                    (row - 5, col),
                    (row - 6, col),
                    (row - 7, col),
                ],
                [
                    (row, col + 1),
                    (row, col + 2),
                    (row, col + 3),
                    (row, col + 4),
                    (row, col + 5),
                    (row, col + 6),
                    (row, col + 7),
                ],
                [
                    (row, col - 1),
                    (row, col - 2),
                    (row, col - 3),
                    (row, col - 4),
                    (row, col - 5),
                    (row, col - 6),
                    (row, col - 7),
                ]
            ]
